WebAS/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebAS.Models;

namespace WebAS.Controllers
{
    [Authorize]
    public class LocationController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Map
        public async Task<ActionResult> Map()
        {
            return View(await db.Locations.ToListAsync());
        }

        // GET: Location
        public async Task<ActionResult> Index()
        {
            return View(await db.Locations.ToListAsync());
        }

        // GET: Location/Details/5
        public async Task<ActionResult> Details(int? id, string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = await db.Locations.FindAsync(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // GET: Location/Create
        public ActionResult Create(string Latitude, string Longitude, string Altitude, string Title, string Description)
        {
            return View();
        }

        // POST: Location/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "LocationId,Latitude,Longitude,Altitude,Title,Description")] Location location)
        {
            if (ModelState.IsValid)
            {
                db.Locations.Add(location);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(location);
        }

        // GET: Location/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = await db.Locations.FindAsync(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Location/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "LocationId,Latitude,Longitude,Altitude,Title,Description")] Location location)
        {
            if (ModelState.IsValid)
            {
                db.Entry(location).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction(ViewBag.BackUrl);
                //return RedirectToAction("Index");
            }
            return View(location);
        }

        // GET: Location/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = await db.Locations.FindAsync(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Location/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Location location = await db.Locations.FindAsync(id);
            db.Locations.Remove(location);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> GetLocations()
        {
            var locations = await db.Locations.ToListAsync();

            return Json(locations, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> GetLocation(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Location location = await db.Locations.FindAsync(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            
            return  Json(location, JsonRequestBehavior.AllowGet);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebAS/Views/Shared/_HeaderMenuPartial.cshtml
@using Microsoft.AspNet.Identity
@using WebAS.Resources;

@if (Request.IsAuthenticated)
{
    <ul class="nav navbar-nav navbar-left">
        @*<li>@Html.ActionLink(@Resources.ViewMsg.ActionLinkHome, "Index", "Home")</li>*@
        @*<li>@Html.ActionLink("Map", "Index", "Map")</li>
        <li>@Html.ActionLink("Locations", "Index", "Locations")</li>
        <li>@Html.ActionLink("Layers", "Index", "Layers")</li>*@

        <li>@Html.ActionLink(@ViewResource.ActionLinkMap, "Map", "Location")</li>
        <li>@Html.ActionLink(@ViewResource.ActionLinkLocations, "Index", "Location")</li>

        @*<li>@Html.ActionLink(@Resources.ViewMsg.ActionLinkAbout, "About", "Home")</li>
            <li>@Html.ActionLink(@Resources.ViewMsg.ActionLinkContact, "Contact", "Home")</li>*@

        @if (User.IsInRole("Admin"))
        {
            @*<li>@Html.ActionLink("ClaimsList", "ClaimsList", "Home")</li>*@
            <li>@Html.ActionLink(@ViewResource.ActionLinkRegisterAccountRegisterLink, "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
        }
    </ul>
}

WebAS/Views/Shared/_Layout.cshtml
@using WebAS.Resources;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @Resource.ApplicationName</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(Resource.ApplicationName, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @Html.Partial("_HeaderMenuPartial")
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @Resource.ApplicationName</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>